#!/usr/bin/env sh

echo '
INFO: This project has a pre-commit hook to execute linting, automatically fixing issues when possible.
If necessary, you can disable this with the "--no-verify" flag during the commit.
Example:
    "git commit -m <message> --no-verify"
'

pnpm run lintStaged && \
pnpm run test || \
{
  echo "ERROR: Linting or tests failed. Please address the issues before committing."
  exit 1
}
